kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: managed-nfs-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard