apiVersion: v1
kind: Pod
metadata:
  name: pods-simple-pod
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: pods-simple-container
      volumeMounts:
        - mountPath: /opt/test/pvc
          name: volume-pvc
  volumes:
    - name: volume-pvc
      persistentVolumeClaim:
        claimName: retain-local-claim 
