kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: retain-local-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ki 
  storageClassName: retain-policy

